"""Add invoice fields to order

Revision ID: 7b6f70ed1b0a
Revises: 
Create Date: 2025-03-11 11:50:29.867920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6f70ed1b0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payment_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('paid_at')
        batch_op.drop_column('payment_details')
        batch_op.drop_column('invoice_id')

    # ### end Alembic commands ###
